
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getConfig() : Promise<string> {
    return await TAURI_INVOKE("get_config");
},
async setConfig(tasksDir: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_config", { tasksDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readTextFile(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_text_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeTextFile(path: string, contents: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_text_file", { path, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeTextFileAtomic(path: string, contents: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_text_file_atomic", { path, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readDir(path: string) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeFile(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createDir(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openTerminal(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_terminal", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runProjectCommand(cmd: string, workingDir: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_project_command", { cmd, workingDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeLogEntry(entry: LogEntry) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_log_entry", { entry }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runClaude(prompt: string, model: string, sessionId: string | null, workingDir: string | null, runId: string, allowedTools: string[] | null, skipPermissions: boolean | null) : Promise<Result<RunResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_claude", { prompt, model, sessionId, workingDir, runId, allowedTools, skipPermissions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runCli(command: string, args: string[], workingDir: string | null, runId: string) : Promise<Result<RunResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_cli", { command, args, workingDir, runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recursive count of every status across the tree.
 * 
 * Uses `u32` (not `usize`) because specta refuses to bridge `usize` to TS:
 * a 64-bit count would overflow `Number.MAX_SAFE_INTEGER`. `u32` is plenty
 * for any realistic task tree (4 billion tasks).
 */
async taskCountByStatus(tasks: Task[]) : Promise<{ [key in TaskStatus]: number }> {
    return await TAURI_INVOKE("task_count_by_status", { tasks });
},
/**
 * Subtree completion percentage (0..=100) or `None` for a leaf with no
 * subtasks.
 */
async taskCalcProgress(task: Task) : Promise<number | null> {
    return await TAURI_INVOKE("task_calc_progress", { task });
},
/**
 * True when this task and every descendant is `Done`.
 */
async taskIsFullyDone(task: Task) : Promise<boolean> {
    return await TAURI_INVOKE("task_is_fully_done", { task });
},
/**
 * DFS path of ids to the first non-`Done` descendant, or `None` when nothing
 * is left to run.
 */
async taskFindNextRunnable(task: Task) : Promise<string[] | null> {
    return await TAURI_INVOKE("task_find_next_runnable", { task });
},
/**
 * Snapshot of the current registry. Returned as `Vec<Agent>` so the TS side
 * can drop it straight into its render cache.
 */
async agentList() : Promise<Agent[]> {
    return await TAURI_INVOKE("agent_list");
},
/**
 * Resolve which agent + model should run a given task. The frontend uses
 * this for both the play button (to pick the provider) and the activity
 * log (to record which agent ran).
 */
async agentResolve(task: Task) : Promise<ResolvedAgent> {
    return await TAURI_INVOKE("agent_resolve", { task });
},
/**
 * Append a new agent to the registry. Returns an error string if the id
 * is already taken so the Agent Manager modal can surface a toast.
 */
async agentAdd(agent: Agent) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_add", { agent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Patch an existing agent in place. Missing fields are left untouched;
 * missing id is a no-op (matches the legacy TS semantics).
 */
async agentUpdate(id: string, patch: AgentPatch) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_update", { id, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove an agent by id. Missing id is a no-op so the Agent Manager modal
 * can fire-and-forget without checking the result first.
 */
async agentRemove(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_remove", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Replace the entire registry — used at startup when the dashboard loads
 * `Database.agents` from disk. Empty / null input falls back to defaults.
 */
async agentReplaceAll(saved: Agent[] | null) : Promise<void> {
    await TAURI_INVOKE("agent_replace_all", { saved });
},
/**
 * Validate a patch's shape. Cheap: only checks the rules that survive
 * serde deserialization (version compat, etc.). Returns `Ok(())` for
 * well-formed patches, `Err(reason)` otherwise.
 */
async patchValidate(patch: Patch) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("patch_validate", { patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apply a single patch to the supplied `Database` and return the mutated
 * db. The TS caller passes the current in-memory db, receives the new one,
 * and writes it back to disk.
 */
async patchApplyToDb(db: Database, patch: Patch) : Promise<Result<Database, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("patch_apply_to_db", { db, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apply a batch of patches in timestamp order, deduplicating against
 * `db.appliedPatches` and the in-memory tracker. Returns the mutated db
 * plus a summary the dashboard can surface in a toast / activity log.
 * 
 * Tuple return is `(Database, ApplyResult)` so the TS side can destructure
 * directly without a wrapper struct.
 */
async patchApplyBatch(db: Database, sources: PatchSource[]) : Promise<[Database, ApplyResult]> {
    return await TAURI_INVOKE("patch_apply_batch", { db, sources });
},
async dbLoad(baseDir: string) : Promise<Result<Database, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("db_load", { baseDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dbSave() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("db_save") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dbGet() : Promise<Result<Database, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("db_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dbReplace(newDb: Database) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("db_replace", { newDb }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dbSetBase(baseDir: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("db_set_base", { baseDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dbWriteMigrationBackup(fromVersion: string, rawText: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("db_write_migration_backup", { fromVersion, rawText }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async patchesApplyPending() : Promise<Result<ApplyResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("patches_apply_pending") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActivityLog = { timestamp: string; agent: string; action: string }
export type Agent = { id: string; label: string; provider: AgentProvider; defaultModel?: string | null; capabilities?: string[]; enabled: boolean; systemPrompt?: string; 
/**
 * Per-agent permission profile from upgrade-01 fix. Optional during migration.
 */
allowedTools?: string[] | null; skipPermissions?: boolean | null; 
/**
 * Generic external CLI provider configuration (provider = "cli").
 */
cliCommand?: string | null; cliArgs?: string[] | null }
/**
 * Sparse update payload for `agent_update`. Every field is optional so the
 * caller can patch a single attribute without echoing the rest. Matches the
 * `Partial<Agent>` shape the TS `agentUpdate` historically accepted.
 * 
 * `default_model` is `Option<Option<String>>` so the frontend can distinguish
 * "leave unchanged" (`undefined`/missing) from "clear it" (`null`). Same
 * convention for `system_prompt` would be wrong because the TS code treats
 * `""` as the cleared state.
 */
export type AgentPatch = { label?: string | null; provider?: AgentProvider | null; defaultModel?: string | null; systemPrompt?: string | null; capabilities?: string[] | null; enabled?: boolean | null; allowedTools?: string[] | null; skipPermissions?: boolean | null; cliCommand?: string | null; cliArgs?: string[] | null }
/**
 * Provider type for an agent (claude CLI vs manual/external).
 */
export type AgentProvider = "claude" | "cli" | "manual"
/**
 * Summary returned by `apply_batch`. The TS dashboard surfaces these counts
 * in a toast and uses `applied_patch_ids` to update its activity log.
 */
export type ApplyResult = { 
/**
 * Patches that mutated the db on this call.
 */
applied: number; 
/**
 * Patches skipped because they were already applied (durable or in-memory).
 */
skipped: number; 
/**
 * Per-patch error messages, prefixed with the offending source id.
 * Errors do NOT abort the batch — every patch is tried independently.
 */
errors: string[]; 
/**
 * Source ids that mutated the db, in apply order. Useful for the
 * dashboard's activity log.
 */
appliedPatchIds: string[] }
/**
 * Discriminated union of patch operations. Tagged on `type` to match the
 * existing JSON wire format that the JS dashboard already produces.
 */
export type Change = { type: "status_change"; projectId: string; taskId: string; from?: TaskStatus | null; to: TaskStatus; note?: string | null } | { type: "add_project"; project: Project } | { type: "add_task"; projectId: string; parentTaskId: string | null; task: Task } | { type: "update_task"; projectId: string; taskId: string; updates: JsonValue; note?: string | null } | { type: "files_modified"; projectId: string; taskId: string; files: string[] } | { type: "add_log"; projectId: string; taskId: string; log: ActivityLog }
export type Database = { version?: string | null; 
/**
 * Set by Phase 1.4 migrations once they land; until then `version`
 * stays canonical.
 */
schemaVersion?: string | null; lastUpdated: string; projects?: Project[]; agents?: Agent[] | null; 
/**
 * Patch identifiers that have already been applied — see
 * fileops.ts:patchIdentity.
 */
appliedPatches?: string[] | null; 
/**
 * Free-form metadata block (`forAI`, `patchPattern`, examples). Kept as
 * an opaque JSON value so Rust never has to interpret it. The leading
 * underscore is preserved on the wire by the explicit `rename`.
 */
_instructions?: JsonValue | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }
export type LastNote = { timestamp: string; agent: string; summary: string }
export type LogEntry = { timestamp: string; level: string; module: string; message: string; context?: JsonValue | null }
export type Patch = { version: string; timestamp: string; agent: string; changes: Change[]; 
/**
 * Marker written when a patch could not be deleted; treated as
 * already-applied. Stays as `_applied` (underscore prefix) on the wire.
 */
_applied?: boolean | null }
/**
 * Patch + caller-supplied source id. The id is typically the patch's
 * filename so the durable `appliedPatches` list can dedupe across runs.
 */
export type PatchSource = { id: string; patch: Patch }
export type Project = { id: string; name: string; description?: string | null; goal?: string | null; workingDir?: string | null; runCommand?: string | null; color: string; createdAt: string; tasks?: Task[]; agentDefaults?: ProjectAgentDefaults | null }
export type ProjectAgentDefaults = { planner?: string | null; executor?: string | null; reviewer?: string | null }
/**
 * Resolved agent + model for a task. Returned by `agent_resolve` over IPC so
 * the frontend only needs one round-trip per task to know which provider /
 * model / system-prompt to invoke.
 */
export type ResolvedAgent = { agentId: string; label: string; provider: AgentProvider; model: string; systemPrompt: string }
export type Review = { timestamp: string; action: ReviewAction; comment: string; reviewer: string }
export type ReviewAction = "approved" | "request_changes"
export type RunEntry = { timestamp: string; model?: string | null; agentId?: string | null; summary?: string | null; sessionId?: string | null; outputFile?: string | null; 
/**
 * Token usage and cost captured from Anthropic's `result` line.
 * Omitted when absent so old tasks.json entries without this field
 * still deserialize cleanly.
 */
tokens?: TokenUsage | null }
export type RunResult = { output: string; sessionId: string | null; 
/**
 * Token usage and cost from Anthropic's `result` line. `None` when the
 * stream ended without producing a result line (e.g. process killed).
 */
usage?: TokenUsage | null }
/**
 * Recursive task node. Each task may own zero-or-more `subtasks`; Rust handles
 * the recursion cleanly because `Vec<Task>` is heap-allocated, so no `Box`
 * indirection is required.
 */
export type Task = { id: string; title: string; description?: string; status: TaskStatus; priority: TaskPriority; agentId?: string | null; aiAgent?: string | null; model?: string | null; prompt?: string | null; tags?: string[]; subtasks?: Task[]; filesModified?: string[]; lastSessionId?: string | null; runHistory?: RunEntry[] | null; lastNote?: LastNote | null; reviews?: Review[] | null; activityLog?: ActivityLog[] | null; createdAt: string; updatedAt?: string | null; completedAt?: string | null }
/**
 * Priority bucket. Matches TS `TaskPriority`.
 */
export type TaskPriority = "low" | "medium" | "high"
/**
 * Task workflow state. Matches TS `TaskStatus` string-union exactly.
 */
export type TaskStatus = "todo" | "in_progress" | "pending_review" | "done" | "blocked"
/**
 * Token usage + cost captured from the `result` line of a Claude stream.
 * All fields default to zero when absent so callers don't have to special-case
 * missing sub-fields.
 * 
 * Token counts use `u32` (not `u64`) because specta maps `u64` to TS BigInt
 * which breaks JSON serialization. `u32` supports up to ~4 billion tokens,
 * far beyond any realistic single invocation.
 */
export type TokenUsage = { inputTokens: number; outputTokens: number; cacheCreationInputTokens: number; cacheReadInputTokens: number; 
/**
 * Authoritative cost as returned by Anthropic — do NOT recompute
 * from token counts because model rates change over time.
 */
totalCostUsd: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
